--- 
id: karolinska/kithemev3_components
title: ki mobile web app theme 
description: ki mobile web app theme 
license: commercial 
version: 1.1.1 
dependencies: 
    kurogo/kurogo-core: 
    - '~> 2.3.0' 
... 
